### ISSUE TITLE
not responding

### ISSUE THREAD

**Issue by Trapulo** [muebel/gestioip-docker-compose#1]
Hi,
I've started docker containers, but nothing responds on port 80. What's wrong?

Maybe something wrong in the .env file? It's not so clear IP addresses requested..

thanks

**Comment by muebel** [comment]
Hi
What is the output of the following commands:

docker ps -a
netstat -ntl
docker logs gip

Regards

**Comment by Trapulo** [comment]
Hi,
containers are running:
CONTAINER ID   IMAGE                    COMMAND                  CREATED       STATUS                   PORTS                 NAMES
279e3b11f982   gestioip/gestioip:3555   "/gestioip_install/s…"   2 days ago    Up 18 seconds            0.0.0.0:80->80/tcp    gip
b83f716e98ab   mysql:5                  "docker-entrypoint.s…"   2 days ago    Up 18 seconds            3306/tcp, 33060/tcp   gip-mysql
8597c9743b3a   hello-world              "/hello"                 12 days ago   Exited (0) 12 days ago                         elegant_panini


netstat -ntl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN

[I confirm I can connect to SSH]

docker logs gip
 * Stopping internet superserver xinetd
   ...done.
 * Starting internet superserver xinetd
   ...done.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Synchronizing state of vsftpd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable vsftpd
Removed /etc/systemd/system/multi-user.target.wants/vsftpd.service.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.77.38.110. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.77.38.110. Set the 'ServerName' directive globally to suppress this message
[Fri Jan 22 17:32:24.825453 2021] [mpm_event:notice] [pid 45:tid 140338408823872] AH00489: Apache/2.4.41 (Ubuntu) mod_perl/2.0.11 Perl/v5.30.0 configured -- resuming normal o                                                 perations
[Fri Jan 22 17:32:24.825556 2021] [core:notice] [pid 45:tid 140338408823872] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.77.38.110. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.77.38.110. Set the 'ServerName' directive globally to suppress this message
[Mon Jan 25 08:06:47.191753 2021] [core:warn] [pid 10:tid 140556702936128] AH00098: pid file /var/run/apache2/apache2.pid overwritten -- Unclean shutdown of previous Apache r                                                 un?
[Mon Jan 25 08:06:47.221825 2021] [mpm_event:notice] [pid 10:tid 140556702936128] AH00489: Apache/2.4.41 (Ubuntu) mod_perl/2.0.11 Perl/v5.30.0 configured -- resuming normal o                                                 perations
[Mon Jan 25 08:06:47.221834 2021] [core:notice] [pid 10:tid 140556702936128] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

thanks

**Comment by muebel** [comment]
Thank you, Trapulo. That looks OK.

Do you have ip_forwarding enabled?

Regards

**Comment by Trapulo** [comment]
root@debian-misc:/home/# cat /proc/sys/net/ipv4/ip_forward
1

**Comment by muebel** [comment]
try
telnet SERVER_IP 80

output should be something like

telnet 192.168.1.200 80
Trying 192.168.1.200...
Connected to 192.168.1.200.
Escape character is '^]'.

**Comment by muebel** [comment]
If the output of the telnet.... command is not the same as the from the example above, check the local firewall rules of the server.

**Comment by Trapulo** [comment]
Tried before to open the ticket :(

root@debian-misc:/home/# telnet 10.77.38.101 80
Trying 10.77.38.101...
Connected to 10.77.38.101.
Escape character is '^]'.
Connection closed by foreign host.

also
root@debian-misc:/home/curl http://localhost                               
curl: (56) Recv failure: Connection reset by peer

**Comment by muebel** [comment]
whats the output of the following command?
ip add

**Comment by Trapulo** [comment]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:62:64:0f brd ff:ff:ff:ff:ff:ff
    inet 10.77.38.101/25 brd 10.77.38.127 scope global dynamic eth0
       valid_lft 596820sec preferred_lft 596820sec
    inet6 fe80::215:5dff:fe62:640f/64 scope link
       valid_lft forever preferred_lft forever
3: br-a49601802a48: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:69:b7:c3:a1 brd ff:ff:ff:ff:ff:ff
    inet 10.77.38.1/25 brd 10.77.38.127 scope global br-a49601802a48
       valid_lft forever preferred_lft forever
    inet6 fe80::42:69ff:feb7:c3a1/64 scope link
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:c5:90:c2:de brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
6: vethe515fdd@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-a49601802a48 state UP group default
    link/ether 62:81:eb:3b:c3:29 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::6081:ebff:fe3b:c329/64 scope link
       valid_lft forever preferred_lft forever
8: veth6bcf83f@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-a49601802a48 state UP group default
    link/ether 5e:a2:18:c7:f4:99 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::5ca2:18ff:fec7:f499/64 scope link
       valid_lft forever preferred_lft forever

**Comment by muebel** [comment]
Generally the problem is that you can reach the host, but not the container.

It seems that the docker network is not listed. Did you made changed the network address in .env?

what's the output of 

docker network ls

?

**Comment by Trapulo** [comment]
root@debian-misc:/tmp/gestioip-docker-compose# docker network ls
NETWORK ID     NAME                              DRIVER    SCOPE
11abe73cf744   bridge                            bridge    local
a49601802a48   gestioip-docker-compose_gip-net   bridge    local
8f7d1b58f2d0   host                              host      local
87fd75a0a83b   none                              null      local


# docker network (bridged network address)
SUBNET="10.77.38.0/25"
GATEWAY="10.77.38.1"
GIP_IP="10.77.38.110"
MYSQL_IP="10.77.38.111"

I tried to delete containers and recreate then, also assigning different IPs, but nothing :(
Also a telnet to MySQL port 3306 fails.

**Comment by muebel** [comment]
To check that the Apache is really listening on port 80 please log in to the gestioip container

docker exec -it gip bash

and execute there

netstat -ntl

**Comment by muebel** [comment]
On the host please execute also

sudo iptables -L DOCKER -n

**Comment by Trapulo** [comment]
netstat from the docker system: 

root@17fb12fa2d2e:/gestioip_install# netstat -ntl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.11:38969        0.0.0.0:*               LISTEN

iptables is not installed:
root@debian-misc:/home/#  iptables -L DOCKER -n
bash: iptables: command not found

**Comment by Trapulo** [comment]
I also tried a ping from the docker image and it seems not working. It can ping only 10.77.38.110 and 10.77.38.111 (the two dockers) but not external IPs.

**Comment by muebel** [comment]
There are firewall rule required which forward traffic from the docker_host port 80 to the container port 80 and which masquerade the private container address with the one of the docker host. That requires that iptables is installed. Docker will create the required rule automatically.

So I think install iptables and restart docker should resolve the issue.

**Comment by Trapulo** [comment]
sorry, iptables is installed. The command may be called with sudo also if I entered su context before.

root@debian-misc:/home/# sudo iptables -L DOCKER -n
Chain DOCKER (2 references)
target     prot opt source               destination
ACCEPT     tcp  --  0.0.0.0/0            10.77.38.110         tcp dpt:80

I think this is the rule you was looking for, so also this is ok :(

**Comment by muebel** [comment]
yes, it is.

The other should appear if you type

sudo iptables -L DOCKER -n -t nat

I suppose it appears, too?

**Comment by muebel** [comment]
Please start tcpdump on the briged docker interface of the docker-host. You can identify it with the command

ip add
...
81: **br-af3b4923164a**: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:90:1f:3f:bd brd ff:ff:ff:ff:ff:ff
    inet 10.77.38.1/25 brd 10.77.38.127 scope global br-af3b4923164a
...

sudo tcpdump -i br-af3b4923164a not port mysql

Then try to access to http://IP_DOCKER_HOST

Does there appear traffic?

**Comment by Trapulo** [comment]
> 
> 
> yes, it is.
> 
> The other should appear if you type
> 
> sudo iptables -L DOCKER -n -t nat
> 
> I suppose it appears, too?

root@debian-misc:/home/# sudo iptables -L DOCKER -n -t nat
Chain DOCKER (2 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
DNAT       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:10.77.38.110:80

**Comment by muebel** [comment]
Trapulo, I just revised the output of the command "ip add" you posted before.
There appears the interface eth0 with a IP of the range of the docker network. That is not the default and might cause problems.

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
link/ether 00:15:5d:62:64:0f brd ff:ff:ff:ff:ff:ff
inet 10.77.38.101/25 brd 10.77.38.127 scope global dynamic eth0
valid_lft 596820sec preferred_lft 596820sec
inet6 fe80::215:5dff:fe62:640f/64 scope link
valid_lft forever preferred_lft forever
3: br-a49601802a48: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
link/ether 02:42:69:b7:c3:a1 brd ff:ff:ff:ff:ff:ff
inet 10.77.38.1/25 brd 10.77.38.127 scope global br-a49601802a48
valid_lft forever preferred_lft forever
inet6 fe80::42:69ff:feb7:c3a1/64 scope link
valid_lft forever preferred_lft forever

Was there a special reason why you changed the the IP range of the docker network? Typically, the docker-host has only the bridged interface in the docker-network. I could imagine that this might cause a routing problem. Maybe the packets are routed to the interface eth0 and not to br-a49601802a48. Please execute "netstat -nr" to check this.

Nevertheless you should use a different network range for the docker network. Please try the following. Delete all containers and networks. Delete the content of mysql/data/. Change the network and IP addresses of the .env file to the default values. Then execute "docker up -d" and try if you can access by browser.

**Comment by Trapulo** [comment]
> 
> 
> Trapulo, I just revised the output of the command "ip add" you posted before.
> There appears the interface eth0 with a IP of the range of the docker network. That is not the default and might cause problems.
> 
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
> link/ether 00:15:5d:62:64:0f brd ff:ff:ff:ff:ff:ff
> inet 10.77.38.101/25 brd 10.77.38.127 scope global dynamic eth0
> valid_lft 596820sec preferred_lft 596820sec
> inet6 fe80::215:5dff:fe62:640f/64 scope link
> valid_lft forever preferred_lft forever
> 3: br-a49601802a48: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
> link/ether 02:42:69:b7:c3:a1 brd ff:ff:ff:ff:ff:ff
> inet 10.77.38.1/25 brd 10.77.38.127 scope global br-a49601802a48
> valid_lft forever preferred_lft forever
> inet6 fe80::42:69ff:feb7:c3a1/64 scope link
> valid_lft forever preferred_lft forever
> 
> Was there a special reason why you changed the the IP range of the docker network? Typically, the docker-host has only the bridged interface in the docker-network. I could imagine that this might cause a routing problem. Maybe the packets are routed to the interface eth0 and not to br-a49601802a48. Please execute "netstat -nr" to check this.
> 
> Nevertheless you should use a different network range for the docker network. Please try the following. Delete all containers and networks. Delete the content of mysql/data/. Change the network and IP addresses of the .env file to the default values. Then execute "docker up -d" and try if you can access by browser.

leaving default settings caused an error running docker compose (something as "the specified address is not compatible with your network"), so I did imagine that it was required a configuration that reflect my LAN (10.77.38.0/25 in my subnet).
I will clear all and update you ASAP, thanks

**Comment by Trapulo** [comment]
I solved!
I removed containers, network, git clone folder, and restarted all without to change .env. This fixed.

Last days I did same many times, but I didn't run "docker network prune" (sorry, I don't know docker very well). 

I suggest to explain in readme that .env may not be changed (you say "Edit the .env file"), or something to explain network settings.

thanks for your assistance!

**Comment by muebel** [comment]
I'm happy to hear that the problem is resolved.

Regards
